example1:
	gcc con_ex1.c -o runme

example2:
	gcc con_ex2.c -o runme -lpthread

example3:
	gcc con_ex3.c -o runme -lpthread

example4:
	gcc con_ex4.c -o runme -lpthread

example5:
	gcc con_ex5.c -o runme -lpthread

.PHONY: clean
clean:
	rm -f runme
	rm -f *.o
